name: Predict Release Version

on:
  pull_request:
    branches: [ '*' ]

jobs:
  PredictReleaseVersion:
    name: PR Comment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.CI_READ_GH_TOKEN }}
    - name: run a script
      id: script_result
      run: |
        echo "Some result"
        pip install python-semantic-release
        semantic-release version --noop
        MESSAGE=$(semantic-release version --noop 2>&1 | tail -n 1)
        VERSION_CHANGE=${MESSAGE##*bumped from }
        MESSAGE="\`python-semantic-release\` expects change to release version: <b><u>$VERSION_CHANGE</u></b>"
        echo "::set-output name=MESSAGE::$(echo $MESSAGE)"
        echo "::set-output name=VERSION_CHANGE::$(echo $VERSION_CHANGE)"
    - name: Comment on PR
      uses: unsplash/comment-on-pr@v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "${{ steps.script_result.outputs.MESSAGE }}\n\n Warning: this comment may be out of date, if any other PRs have been merged since the comment was made."
        check_for_duplicate_msg: true
        duplicate_msg_pattern: "^.*expects change to release version.*${{ steps.script_result.outputs.VERSION_CHANGE }}.*$"
